# this is the local config that will only be used as fallback in case the config server is unavailable
spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://licensingservice_database:5432/licenses"
    username: "postgres"
    password: "{cipher}0adb1f9fe2f1ec3421dde8045a76a1d361f06bba3ce11490b2be9846db6608f4"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.postgresql.Driver"
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://eurekaservice:8761/eureka/"
example:
  property: "I AM THE DEFAULT"
