# this is the local config that will only be used as fallback in case the config server is unavailable
spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://licensingservice_database:5432/licenses"
    username: "postgres"
    password: "p0stgr@s"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.postgresql.Driver"
  redis:
     host: redis
     port: 6379

  cloud:
    stream:
      bindings:
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
#        inboundOrgChanges:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup
      kafka:
        binder:
          zkNodes: "http://kafkaserver:2181"
          brokers: "http://kafkaserver:9092"

management:
  endpoints:
    web:
      exposure:
        include: env, health, metrics, info

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://eurekaservice:8761/eureka/"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    SpringMicroservicesInAction.LicensingService: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    getLicensesByOrganizationCommand:
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 70
    getLicenseCommand:
      circuitBreaker:
        requestVolumeThreshold: 10
        errorThresholdPercentage: 80
  threadpool:
    getLicensesByOrganizationThreadPool:
      coreSize: 20
      maxQueueSize: 10
    getLicenseThreadPool:
      coreSize: 30
      maxQueueSize: 20

example:
  property: "I AM THE DEFAULT"
