# this is the default config that will be loaded in case the config service does not provide a config
spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://organizationservice_database:5432/organizations"
    username: "postgres"
    password: "p0stgr@s"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "org.postgresql.Driver"

  cloud:
    stream:
      bindings:
        output:
          destination:  orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes: "http://kafkaserver:2181"
          brokers: "http://kafkaserver:9092"

example:
  property: "I AM THE DEFAULT"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://eurekaservice:8761/eureka/"

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1000
    updateOrganizationCommandKey:
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 70
  threadpool:
    updateOrganizationThreadPool:
      coreSize: 20
      maxQueueSize: 10
    getOrganizationThreadPool:
      coreSize: 20
      maxQueueSize: 10

logging:
  level:
    com.netflix: WARN
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN
    SpringMicroservicesInAction.OrganizationService: DEBUG

application:
  timeout:
    enabled: false
